remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [AquaKube]
description: [Bring advanced technology to aquaculture with open source software, hardware, and data models]